Update README.md to reflect changes made to release artifacts and installation instructions
cert-manager/openshift-routes pull request #82
Opened 2024-08-14 10:34 UTC by inteon

These changes reflect the new processes starting from v0.6.0: https://github.com/cert-manager/openshift-routes/releases/tag/v0.6.0

2024-08-14 14:29 UTC, SgtCoDFish requested changes
I like the changes to the README, but I think the RELEASE file needs updating before it can be merged!

2024-08-14 14:29 UTC, SgtCoDFish commented on RELEASE.md
> +    approver-policy provides a policy engine for certificates issued by cert-manager!
suggestion: Copy past mistake!

2024-08-14 14:29 UTC, SgtCoDFish commented on RELEASE.md
> +[releases page]: https://github.com/cert-manager/approver-policy/releases
suggestion: Both copied and need updating.

2024-08-15 15:46 UTC, inteon commented
> I like the changes to the README, but I think the RELEASE file needs updating before it can be merged!

Thanks, I did blindly copy RELEASE.md, and forgot to update it. Should be fixed now.

2024-08-22 11:53 UTC, inteon commented
/approve

2024-08-28 09:29 UTC, SgtCoDFish approved these changes
/lgtm
/approve

2024-08-28 09:37 UTC, merged